'use strict';
const assert=require('assert'),fs=require('fs');
const {diagnose}=require('../scripts/diagnose_commissioning');
const e=JSON.parse(fs.readFileSync('./evidence/commissioning.json','utf8'));
const d=diagnose(e);
assert.equal(d.schema,'cartpole-diagnosis/v1');
const ids=new Set(d.findings.map(x=>x.id));
for(const id of ['D01_MODEL_ID','D02_ACTUATOR_ID','D03_ESTIMATOR_CALIBRATION','D04_CONTROLLER_TUNING','D04A_CONTROL_ESTIMATION_COTUNING','D04B_MPC_TUNING','D04C_MODEL_HIERARCHY','D04D_ROBUST_MPC_FORMULATION','D04E_SAFETY_SUPERVISOR','D05B_SENSOR_FAULTS','D05C_ACTUATOR_ENVELOPE','D05D_DISCRETIZATION','D08_REALTIME','D09_COMBINED_SIM2REAL'])assert(ids.has(id),id);
assert.equal(d.findings.find(x=>x.id==='D03_ESTIMATOR_CALIBRATION').status,'PASS');
assert.equal(d.findings.find(x=>x.id==='D04_CONTROLLER_TUNING').status,'REJECT');
assert.equal(d.findings.find(x=>x.id==='D04A_CONTROL_ESTIMATION_COTUNING').status,'REJECT');
assert.equal(d.findings.find(x=>x.id==='D05D_DISCRETIZATION').status,'INVESTIGATE');
assert.notEqual(d.findings.find(x=>x.id==='D08_REALTIME').status,'PASS','solver-only timing cannot certify end-to-end real-time admission');
console.log(JSON.stringify({findings:d.findings.map(x=>({id:x.id,status:x.status}))},null,2));
