"""The recovery claim must be regenerated by normal CI, not just a stored receipt."""
from pathlib import Path
import unittest
import subprocess
import tempfile
ROOT=Path(__file__).resolve().parents[1]
class RecoveryWorkflowContract(unittest.TestCase):
    def test_recovery_and_scheduler_are_in_existing_job(self):
        workflow=(ROOT/'.github/workflows/verify.yml').read_text()
        required=['node tests/test_wheelbot_runtime.mjs',
                  'node scripts/validate_wheelbot_mpc.mjs --recovery',
                  'python tests/test_wheelbot_recovery_reference.py',
                  'python tests/test_wheelbot_recovery_ci_contract.py']
        for command in required:
            self.assertIn(command,workflow)
        self.assertLess(workflow.index(required[1]),workflow.index(required[2]))
        for artifact in ['evidence/wheelbot_mpc_recovery_validation.json',
                         'evidence/wheelbot_recovery_reference.json',
                         'evidence/wheelbot_contact_diagnosis.json']:
            self.assertIn(artifact,workflow)
    def test_performance_cannot_silently_compare_to_itself(self):
        source=(ROOT/'tests/test_wheelbot_mpc_performance.mjs').read_text()
        self.assertIn('An exact baseline source is required',source)
        self.assertNotIn("baseline??'self'",source)
    def test_missing_or_wrong_baseline_rejected_before_benchmark(self):
        missing=subprocess.run(['node','tests/test_wheelbot_mpc_performance.mjs'],cwd=ROOT,text=True,capture_output=True)
        self.assertNotEqual(missing.returncode,0)
        self.assertIn('An exact baseline source is required',missing.stderr)
        (ROOT/'test-results').mkdir(exist_ok=True)
        with tempfile.TemporaryDirectory(dir=ROOT/'test-results') as directory:
            wrong=Path(directory)/'wrong.mjs';wrong.write_text('// not the audited baseline\n')
            bad=subprocess.run(['node','tests/test_wheelbot_mpc_performance.mjs',str(wrong)],cwd=ROOT,text=True,capture_output=True)
            self.assertNotEqual(bad.returncode,0)
            self.assertIn('unexpected pre-optimization source',bad.stderr)
if __name__=='__main__':unittest.main()
