import fs from 'node:fs';
import assert from 'node:assert/strict';
const html=fs.readFileSync('wheelbot.html','utf8');
const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);
assert.equal(new Set(ids).size,ids.length);
for(const id of ['view','target-x','target-z','target-pitch','target-mode','target-action','cancel','status'])assert(ids.includes(id));
for(const id of ['robot-model','design','mode','reference-experiments','physical-editor'])assert(!ids.includes(id));
assert(html.includes('hip axis')&&html.includes('Wheel centre')&&html.includes('점프 · 검증 대기'));
const app=fs.readFileSync('src/wheelbot_app.mjs','utf8');
assert(app.includes('setPointerCapture')&&app.includes('onpointercancel')&&app.includes('onpointerup'));
assert(!app.includes('mountDesignEditor')&&!app.includes('action_jump.json'));
console.log('One canvas, one physical model, direct path controls PASS');
