// Unit-test the actual animation scheduler without starting a browser/server.
import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {validateWheelbotResponseProfile} from '../src/wheelbot_control.mjs';
const baselineText=fs.readFileSync('assets/wheelbot/profile.json','utf8');
const base=JSON.parse(baselineText),recovery=JSON.parse(fs.readFileSync('assets/wheelbot/recovery_profile.json'));
const hash=crypto.createHash('sha256').update(baselineText).digest('hex');
assert(validateWheelbotResponseProfile({assetSha256:base.assetSha256,limits:base.limitsNm},base,recovery,hash));
const source=fs.readFileSync('src/wheelbot_app.mjs','utf8');
const scheduler=source.slice(source.indexOf('function animate(time)'),source.indexOf('window.wheelbotLab ='));
assert(scheduler.startsWith('function animate(time)'));
const context={playing:true,frameTime:0,accumulated:0,droppedWallSeconds:0,steps:0,draws:0,callbacks:0,backend:{diagnostics:()=>({controlDt:.01})}};
context.tick=draw=>{assert.equal(draw,false,'animation must not redraw for each control sample');context.steps++;};
context.render=()=>{context.draws++;};
context.requestAnimationFrame=()=>{context.callbacks++;};
vm.createContext(context);vm.runInContext(scheduler,context);
context.animate(1000);context.animate(1017);
assert.equal(context.steps,1);assert.equal(context.draws,1);
context.animate(1517);
assert.equal(context.steps,5,'stalled frame executes at most four fixed control steps');
assert.equal(context.draws,2,'stalled frame redraws exactly once');
assert(Math.abs(context.droppedWallSeconds-.467)<1e-10);
assert(context.accumulated>=0&&context.accumulated<.01);
const before=context.steps;context.playing=false;context.animate(2517);assert.equal(context.steps,before);
context.playing=true;context.animate(2527);assert.equal(context.steps,before+1);
assert.equal(context.callbacks,5);
console.log('Recovery profile binding and actual frame scheduler PASS: one redraw, fixed steps, bounded catch-up, pause/resume');
