'use strict';
const CONTROL_LAB_TOPICS = {
 overview:{group:"개요",title:"Controller와 Observer를 한 시스템으로 읽기",lead:"Controller는 무슨 힘을 낼지, Observer는 지금 상태가 무엇인지 푼다. 둘은 직렬 연결되므로 좋은 controller도 나쁜 state estimate 위에서는 무너질 수 있다.",chips:["same plant","same sensor contract","truth = evaluator only"],runtime:null,body:[
  "<div class='section'><h3>먼저 분리한다</h3><div class='math'>Plant:      x(k+1) = f(x(k),u(k))\\nSensor:     y(k) = h(x(k)) + noise\\nObserver:   (y,u) -> x_hat, P\\nController: x_hat -> u</div><div class='take'>plant를 고정하고 controller 또는 observer 하나만 바꾸는 것이 이 lab의 비교 규칙이다.</div></div>",
  "<div class='section'><h3>두 개의 계보</h3><p>Controller는 feedback과 prediction을 확장하고, Observer는 model/geometry에 learning을 어디에 삽입할지 확장한다.</p></div>"
 ].join("")},
 pid:{group:"Controller",title:"PID — 모델 없이 오차에 직접 반응",lead:"pole angle과 angle-rate를 빠르게 잡고 cart position/velocity를 느리게 되돌리는 결합 PID/PD.",chips:["feedback","no plant model","gain tuning"],runtime:{controller:"pid"},body:[
  "<div class='section'><h3>왜 필요한가</h3><p>목표와 실제값의 오차만 있으면 모델을 몰라도 feedback을 만들 수 있다. 대신 여러 state의 trade-off는 사람이 gain에 넣는다.</p></div>",
  "<div class='section'><h3>핵심 식</h3><div class='math'>e_p = p - p*\\nu = k_theta theta + k_omega omega + k_p e_p + k_v v + k_i integral(e_p)dt</div></div>",
  "<div class='section'><h3>Humanoid와 연결</h3><p>MPC/WBC 위에도 actuator 근처 PD feedback이 남을 수 있다. PID는 상위 planner가 아니라 가장 아래 feedback의 직관이다.</p></div>"
 ].join("")},
 lqr:{group:"Controller",title:"LQR — 모델과 비용으로 feedback gain을 계산",lead:"선형 dynamics와 state/control 비용 Q,R에서 Riccati equation으로 K를 계산한다.",chips:["linear model","Riccati","state feedback"],runtime:{controller:"lqr"},body:[
  "<div class='section'><h3>PID에서 무엇이 달라지나</h3><p>gain을 개별 오차마다 손으로 조절하는 대신 A,B,Q,R이 전체 state feedback K를 결정한다.</p></div>",
  "<div class='section'><h3>핵심 식</h3><div class='math'>x(k+1) = A x(k) + B u(k)\\nJ = sum[x^T Q x + u^T R u]\\nu = -Kx</div></div>",
  "<div class='section'><h3>MPC로 가는 다리</h3><p>LQR의 quadratic cost와 Riccati recursion은 MPC/NMPC의 local quadratic subproblem에서도 다시 나온다.</p></div>"
 ].join("")},
 linear_mpc:{group:"Controller",title:"Linear MPC — LQR에 horizon과 입력 제약을 추가",lead:"upright 주변의 discrete A,B로 N-step 미래를 예측하고, |u|<=u_max box constraint 안에서 control sequence를 매 tick 다시 최적화한다.",chips:["finite horizon","receding horizon","box-constrained input"],runtime:{controller:"linear_mpc"},body:[
  "<div class='section'><h3>현재 실제 구현</h3><p>N=30. 공식 MuJoCo WASM plant의 upright discrete Jacobian A,B를 사용하고, 입력 제약을 포함한 QP를 검증된 quadprog Goldfarb–Idnani solver로 푼다. 유한성·제약 위반·KKT 잔차를 검사한 뒤 첫 control만 적용하고 다음 tick에 다시 푼다. 이 solver는 이전 해를 warm start로 사용하지 않는다.</p></div>",
  "<div class='section'><h3>문제</h3><div class='math'>min sum(k=0..N-1) [x_k^T Q x_k + R u_k^2] + x_N^T Q_f x_N\\ns.t. x_(k+1)=A x_k+B u_k\\n     |u_k| <= u_max\\n\\nassemble QP -> quadprog -> check residuals -> apply u_0 -> repeat</div></div>",
  "<div class='section'><h3>예측 구간이 끝난 뒤의 비용</h3><p>Terminal cost는 마지막 상태에서 이후에 남을 제어 부담을 평가한다. Original은 설정된 대각 가중치이고, Riccati는 같은 nominal A,B,Q,R로 계산한 전체 행렬 P를 사용한다. 위치·속도·각도 사이의 결합항도 유지하며, 수렴과 잔차를 검사한다. Linear MPC와 hard-rail MPC의 Terminal cost 선택에서 비교할 수 있다. 이는 local tail-cost 근사이며 terminal invariant set이나 실제 로봇의 안전 보장이 아니다.</p></div>",
  "<div class='section'><h3>한계</h3><p>horizon 전체가 하나의 upright 선형모델이다. 실제 nonlinear plant가 멀어지면 model error가 커진다.</p></div>"
 ].join("")},
 state_mpc:{group:"Controller",title:"State-constrained MPC — input bound만으로는 부족하다",lead:"MPC의 장점은 미래를 보는 것뿐 아니라 state/path constraint를 문제 안에 넣는 데 있다. 현재 browser mode는 cart position에 soft penalty를 넣어 input-only MPC와 차이를 보여준다.",chips:["state constraint","soft penalty","feasibility"],runtime:{controller:"state_mpc"},body:[
  "<div class='section'><h3>입력 제약과 상태 제약은 다르다</h3><div class='math'>input: |u_k| <= u_max\nstate: |p_k| <= p_max\npath: g(x_k,u_k) <= 0</div><p>pole을 세우는 동안 cart가 트랙 끝으로 달아나는 해는 input constraint만으로는 합법일 수 있다.</p></div>",
  "<div class='section'><h3>현재 구현</h3><p>state_mpc는 |p|가 soft boundary를 넘으면 quadratic penalty를 추가하는 비교용 구현이다. 반면 controller 선택의 Constrained MPC · hard rail은 |p_k|<=2.4 m를 quadprog의 선형 제약에 직접 넣는다. 후자는 예측 상태의 제약을 검사하지만, 잡음·모델 오차가 있는 실제 상태의 안전이나 recursive feasibility까지 보장하지 않는다.</p></div>",
  "<div class='section'><h3>Humanoid로 확장</h3><p>joint/velocity/torque limits, torque-speed envelope, friction cone, unilateral contact, CoP/support, collision, swing clearance는 가능한 한 명시적 constraint로 모델링한다. penalty weight로 전부 숨기면 failure mode를 해석하기 어렵다.</p></div>"
 ].join("")},
 ltv_mpc:{group:"Controller",title:"LTV MPC / SQP-RTI — 매 tick 현재 trajectory 주변을 다시 선형화",lead:"고정 upright A,B를 계속 쓰는 Linear MPC와 nonlinear OCP를 여러 번 반복해 푸는 NMPC 사이의 핵심 연결고리다. 현재 warm-start trajectory에서 A_k,B_k를 다시 만들고 한 번의 local quadratic update만 수행한다.",chips:["successive linearization","time-varying A_k,B_k","real-time iteration"],runtime:{controller:"ltv_mpc"},body:[
  "<div class='section'><h3>세 수준을 구분</h3><div class='math'>LTI MPC: one A,B around equilibrium\nLTV / RTI: A_k,B_k = Jacobian along current trajectory, one local update/tick\nNMPC: nonlinear f stays in OCP, multiple local iterations may be used</div></div>",
  "<div class='section'><h3>왜 humanoid에 중요하나</h3><p>실시간 SQP-RTI 계열은 nonlinear robot model을 유지하면서도 매 제어주기 한 번의 linearization/QP step으로 deadline을 맞추는 전형적인 절충이다. contact mode가 고정된 구간에서는 특히 자연스럽다.</p></div>",
  "<div class='section'><h3>현재 CartPole 구현</h3><p>nonlinear nominal rollout → per-stage numerical Jacobian → 한 번의 iLQR/SQP-style backward update → bounded line search → 첫 force 적용. OCS2/acados RTI source port는 아니다.</p></div>"
 ].join("")},
 centroidal_mpc:{group:"Controller",title:"Centroidal-style MPC — reduced planner와 lower-level realization",lead:"Figure의 centroidal OCS2 lane은 momentum/configuration을 state로, contact wrench와 joint velocity를 input으로 최적화하고 inverse dynamics로 joint command를 만든다.",chips:["reduced-order","momentum","planner -> lower level"],runtime:{controller:"centroidal_mpc"},body:[
  "<div class='section'><h3>Figure pinned comparator의 실제 구조</h3><div class='math'>x = [h, q_b, q_j]\\nh = [v_com, L/m]\\nu = [W_left, W_right, qdot_j]\\n\\ncentroidal dynamics + state/input cost + ICP cost\\n+ gait/contact schedule + friction/contact constraints\\n-> SQP policy\\n-> q_des, qdot_des, contact wrench\\n-> inverse dynamics -> tau_ff</div></div>",
  "<div class='section'><h3>CartPole에 적용한 실제 대응</h3><p>발/contact wrench가 없고 pole은 underactuated라 humanoid 식을 그대로 복사하지 않는다. 시스템 전체 수평 CoM을 reduced MPC로 계획하고 look-ahead CoM reference를 full-state inner LQR가 실현한다.</p><div class='math'>M = m_c + m_p\\nc = x + (m_p l/M) sin(theta)\\nc_dot = v + (m_p l/M) cos(theta) omega\\nc_ddot = F_net/M   [ideal horizontal reduced model]\\n\\nouter box-constrained MPC: [c,c_dot] -> future CoM reference\\ninner feedback: [x-x_ref,v-v_ref,theta,omega] -> force</div><div class='take warn'>Figure centroidal OCS2를 포팅했다는 뜻이 아니라, reduced-planner -> lower-level realization 구조를 CartPole 물리에 맞게 구현한 analogue다. 외력 push와 model mismatch는 outer model에 알려주지 않는다.</div></div>",
  "<div class='section'><h3>핵심 trade-off</h3><p>작은 predictive problem을 빠르게 풀 수 있지만 reduced model과 실제 full dynamics 사이 realization gap이 생긴다.</p></div>"
 ].join("")},
 full_nmpc:{group:"Controller",title:"Full nonlinear NMPC — nonlinear plant 자체를 horizon에 넣기",lead:"Figure full-order lane은 q와 qdot 전체를 state로 두고 contact wrench와 joint acceleration을 input으로 최적화한다. CartPole판도 nonlinear f(x,u)를 직접 rollout한다.",chips:["full state","nonlinear rollout","iterative solve"],runtime:{controller:"full_nmpc"},body:[
  "<div class='section'><h3>Figure pinned comparator의 실제 구조</h3><div class='math'>x = [q_b, q_j, qdot_b, qdot_j]\\nu = [W_left, W_right, qddot_j]\\n\\nfull rigid-body acceleration dynamics\\n+ state/input + joint torque costs\\n+ contact/swing/friction constraints\\n-> OCS2 multiple-shooting SQP\\n-> policy -> q_des, qdot_des, torque</div></div>",
  "<div class='section'><h3>CartPole의 실제 solver</h3><p>N=30. 동일 nonlinear Plant.integrate로 nominal trajectory를 rollout하고, 매 stage에서 A_k=d f/dx, B_k=d f/du를 수치 선형화한다. local quadratic backward solve 후 bounded forward line-search를 2회 수행하고 warm-start한다.</p><div class='math'>x_(k+1)=f(x_k,u_k)\\nA_k = df/dx, B_k = df/du\\nquadratic local subproblem\\n-> backward solve\\n-> line search + |u|<=u_max\\n-> apply u_0 only</div></div>",
  "<div class='section'><h3>왜 항상 더 좋은가?</h3><p>아니다. 더 정확한 model을 horizon에 넣는 대신 계산시간, local optimum, model mismatch, estimator error의 영향을 더 직접 받는다.</p></div>"
 ].join("")},
 safety:{group:"Controller",title:"Safety supervisor — 최적제어와 별도로 unsafe prediction을 감시",lead:"좋은 MPC cost가 safety guarantee는 아니다. 현재 bridge는 NMPC predicted trajectory가 cart/angle margin을 넘으면 local LQR backup으로 전환한다.",chips:["runtime monitor","backup controller","degraded mode"],runtime:{controller:"supervised_nmpc"},body:[
  "<div class='section'><h3>현재 executable bridge</h3><div class='math'>u_nom = NMPC(x_hat)\\nif predicted |p| > p_margin or |theta| > theta_margin:\\n    u = LQR_backup(x_hat)\\nelse:\\n    u = u_nom</div><p>large-angle fixed probe에서는 input-only Full NMPC가 track boundary를 넘는 조건에서 backup supervisor가 cart excursion을 줄였다.</p></div>",
  "<div class='section'><h3>이것이 보장하지 않는 것</h3><p>CBF, viability kernel, reachability, invariant terminal set의 formal safety guarantee는 없다. 실제 humanoid에서는 verified backup policy, safety filter, collision/contact constraints, hardware interlock와 함께 별도 safety case가 필요하다.</p></div>",
  "<div class='section'><h3>핵심 교훈</h3><p>controller objective를 더 세게 튜닝하는 것과 safety layer를 두는 것은 같은 일이 아니다. runtime fault/degradation이 있으면 nominal optimizer 밖에서 admissibility를 감시해야 한다.</p></div>"
 ].join("")},
 robust_mpc:{group:"Controller",title:"Robust / stochastic MPC — 모델 하나가 아니라 uncertainty set을 고려",lead:"nominal MPC는 하나의 모델과 하나의 예측을 믿는다. sim2real에서는 parameter uncertainty, disturbance, estimation error를 prediction/constraint margin에 포함해야 한다.",chips:["tube MPC","min-max","chance constraints","scenario MPC"],runtime:null,body:[
  "<div class='section'><h3>대표 계열</h3><div class='math'>Nominal MPC: one model\nTube MPC: nominal trajectory + invariant error tube\nMin-max MPC: optimize worst disturbance in a bounded set\nStochastic MPC: propagate distributions\nChance constraint: P(g(x,u)<=0) >= 1-epsilon\nScenario MPC: enforce sampled uncertainty scenarios</div></div>",
  "<div class='section'><h3>어떤 uncertainty가 어디로 가나</h3><p>잘 식별되는 parametric uncertainty는 model set/domain에, fast zero-mean disturbance는 robust/stochastic term에, estimator uncertainty는 chance/tube margin에, mode/contact ambiguity는 hybrid/scenario layer에 넣는 식으로 분리한다.</p></div>",
  "<div class='section'><h3>현재 CartPole runtime</h3><p><b>Scenario-risk MPC</b>는 서로 다른 mass/pole-mass/length linear models 세 개에 동일한 control sequence를 적용하고, mean cost + risk × (worst - mean)을 최소화한다. 이것은 finite-model ensemble robustification을 실제로 보여주지만 tube invariant set, min-max guarantee, chance-constraint 보장은 없다.</p></div><div class='section'><h3>Figure 경계</h3><p>Humanoid에서는 uncertainty의 종류를 먼저 식별한 뒤 native OCS2/acados formulation에서 tube/scenario/chance/risk-sensitive 방법을 선택한다. Domain randomization과 robust MPC를 같은 말로 쓰면 안 된다.</p></div>"
 ].join("")},
 ppo:{group:"Controller",title:"PPO — runtime solver를 training으로 옮기기",lead:"실행 때 horizon optimization 대신 학습된 actor가 observation에서 action을 낸다.",chips:["learned policy","offline training","cheap inference"],runtime:{controller:"ppo"},body:[
  "<div class='section'><h3>현재 구현</h3><p>기존 CartPole PPO Studio robust final-budget actor를 그대로 사용한다.</p></div>",
  "<div class='section'><h3>구조</h3><div class='math'>observation -> Actor -> pi(left), pi(right)\\ntraining: PPO clipped objective + GAE\\nruntime: network forward -> action</div></div>",
  "<div class='section'><h3>MPC와 차이</h3><p>MPC는 현재 model로 미래를 매번 푼다. PPO는 대응을 training optimization을 통해 weight에 압축한다.</p></div>"
 ].join("")},
 raw:{group:"Observer",title:"Raw sensor — 센서를 그냥 쓰면 왜 안 되나",lead:"p와 theta만 직접 측정하고 v와 omega를 finite difference로 만든다.",chips:["baseline","finite difference","noise amplification"],runtime:{observer:"raw"},body:[
  "<div class='section'><h3>핵심 식</h3><div class='math'>v_hat ~= (p_k-p_(k-1))/dt\\nomega_hat ~= wrap(theta_k-theta_(k-1))/dt</div></div>",
  "<div class='section'><h3>문제</h3><p>작은 measurement noise가 dt로 나뉘면서 velocity noise로 크게 증폭된다.</p></div>"
 ].join("")},
 kf:{group:"Observer",title:"Kalman Filter — prediction과 measurement 신뢰도를 결합",lead:"선형 dynamics로 hidden velocity까지 예측하고 P,Q,R로 sensor correction의 크기를 매 tick 계산한다.",chips:["P Q R","Kalman gain","linear/Gaussian"],runtime:{observer:"kf"},body:[
  "<div class='section'><h3>핵심</h3><div class='math'>x_hat_minus = A x_hat_plus + B u\\nP_minus = A P_plus A^T + Q\\nr = y - H x_hat_minus\\nK = P_minus H^T (H P_minus H^T + R)^-1\\nx_hat_plus = x_hat_minus + K r</div></div>",
  "<div class='section'><h3>hidden state가 왜 고쳐지나</h3><p>A의 dynamics coupling이 P에 cross-covariance를 만들고, measurement residual이 K의 velocity row를 통해 hidden state correction으로 들어간다.</p></div>"
 ].join("")},
 ekf:{group:"Observer",title:"EKF — nonlinear mean, local linear covariance",lead:"state mean은 nonlinear f로 움직이고 covariance 전파에 필요한 Jacobian만 현재점에서 계산한다.",chips:["nonlinear f","Jacobian","local linearization"],runtime:{observer:"ekf"},body:[
  "<div class='section'><h3>KF에서 바뀌는 부분</h3><div class='math'>x_hat_minus = f(x_hat_plus,u)\\nF = df/dx evaluated at x_hat\\nP_minus = F P_plus F^T + Q\\n\\nmeasurement correction은 Kalman 구조 유지</div></div>",
  "<div class='section'><h3>직접 비교</h3><p>Scenario에서 <b>Estimator nonlinear bench · 28.6° · LQR</b>를 선택하고 controller를 LQR로 고정하면 매우 낮은 sensor noise에서 model nonlinearity를 분리할 수 있다. 고정 5-seed probe에서 state RMSE는 KF 약 0.0080, EKF 약 0.00323이었다.</p></div><div class='section'><h3>다음 문제</h3><p>rotation/pose는 평범한 Euclidean vector가 아니므로 error 자체를 어떤 geometry에서 정의할지가 중요해진다.</p></div>"
 ].join("")},
 ukf:{group:"Observer",title:"UKF — Jacobian 대신 sigma points로 nonlinear 분포를 전파",lead:"UKF는 EKF의 상위 버전이 아니라 다른 nonlinear Gaussian approximation이다. Jacobian을 직접 쓰지 않고 deterministic sigma points를 nonlinear plant에 통과시켜 평균과 covariance를 다시 구성한다.",chips:["sigma points","nonlinear propagation","Gaussian belief"],runtime:{observer:"ukf"},body:[
  "<div class='section'><h3>핵심</h3><div class='math'>x,P -> sigma points {chi_i}\\nchi_i^- = f(chi_i,u)\\nx_hat^- = sum W_i chi_i^-\\nP^- = sum W_i (chi_i^- - x_hat^-)(...)^T + Q\\nmeasurement sigma points -> K -> correction</div></div>",
  "<div class='section'><h3>언제 의미가 있나</h3><p>Jacobian 계산이 어렵거나 local linearization error가 큰 smooth nonlinear system에서 유용하다. 하지만 belief가 Gaussian 하나로 표현되기 어렵거나 contact mode가 multimodal이면 UKF만으로 구조 문제가 해결되지는 않는다.</p></div>",
  "<div class='section'><h3>이 CartPole 결과</h3><p>현재 nominal/nonlinear bench에서는 EKF와 UKF가 거의 같은 결과를 낸다. 이것은 UKF가 불필요하다는 뜻이 아니라 현재 4-state smooth dynamics와 noise regime에서 두 Gaussian approximation이 비슷하게 충분하다는 뜻이다.</p></div>"
 ].join("")},
 inekf:{group:"Observer",title:"InEKF — Lie-group symmetry가 있을 때 invariant error를 쓰는 별도 EKF 계열",lead:"InEKF는 EKF의 무조건적인 다음 버전이 아니다. 적절한 Lie-group/group-affine 구조가 있을 때 invariant error로 linearization 특성을 개선한다. CartPole runtime은 SO(2) wrap만 보여준다.",chips:["Lie group","invariant error","contact aided"],runtime:{observer:"so2"},body:[
  "<div class='section'><h3>CartPole runtime bridge</h3><div class='math'>r_theta = wrap(theta_meas-theta_hat_minus)\\ntheta_hat_plus = wrap(theta_hat_minus + delta_theta)\\n\\nexample: +179 deg -> -179 deg\\nEuclidean residual = -358 deg\\nSO(2) residual = +2 deg</div><p>이것은 Hartley InEKF 그 자체가 아니라 angle manifold에서 error 정의가 왜 중요한지 보여주는 micro-bench다.</p></div>",
  "<div class='section'><h3>Hartley에서 실제로 하는 일</h3><div class='math'>state: R, v, p, contact positions d_i\\nIMU propagation + leg FK contact observations\\ninvariant error dynamics\\n\\nunobservable: global translation, global yaw</div></div>",
  "<div class='section'><h3>다음 병목</h3><p>filter가 좋아도 어느 contact measurement를 믿을지 틀리면 update가 오히려 state를 망친다.</p></div>"
 ].join("")},
 mhe:{group:"Observer",title:"MHE — 최근 sensor window 전체를 optimization으로 다시 맞춘다",lead:"KF/EKF가 한 step씩 재귀적으로 갱신하는 것과 달리 MHE는 최근 N개의 state/measurement를 한 window로 묶어 dynamics, measurement, physical constraints를 함께 최적화한다.",chips:["windowed optimization","arrival cost","constraints"],runtime:{observer:"mhe"},body:[
  "<div class='section'><h3>정식 MHE</h3><div class='math'>min  Gamma(x_(k-N))\n   + sum ||w_i||_(Q^-1)^2\n   + sum ||v_i||_(R^-1)^2\ns.t. x_(i+1)=f(x_i,u_i)+w_i\n     y_i=h(x_i)+v_i\n     g(x_i)<=0</div><p>Gamma는 window 이전의 정보를 압축한 arrival cost다. 그래서 단순 sliding least-squares와 다르다.</p></div>",
  "<div class='section'><h3>현재 CartPole runtime</h3><p>작은 browser lab에서는 EKF posterior를 approximate arrival prior로 쓰고, 최근 window의 첫 state 4개만 Gauss-Newton으로 최적화한 뒤 nonlinear plant로 single-shooting한다. process-noise trajectory나 hard state constraint까지 decision variable로 두는 full NMHE는 아니다.</p></div>",
  "<div class='section'><h3>Humanoid로 확장할 때</h3><p>실제 legged/humanoid에서는 orientation EKF/InEKF + velocity/contact MHE처럼 문제를 분해하거나, acados/OSQP 기반 constrained MHE를 쓰는 편이 현실적이다. 2024 EKF+MHE legged 연구는 PogoX/Cassie/Go1에서 200 Hz, 0.1 s window를 실증했다.</p></div>"
 ].join("")},
 consistency:{group:"Observer",title:"Estimator consistency — RMSE가 낮아도 P가 틀리면 잘못된 filter",lead:"state error가 작다는 것과 filter가 자신의 uncertainty를 올바르게 표현한다는 것은 다른 문제다. controller가 covariance를 사용한다면 calibration까지 검증해야 한다.",chips:["NIS","NEES","chi-square","calibration"],runtime:null,body:[
  "<div class='section'><h3>두 통계</h3><div class='math'>NIS = innovation^T S^-1 innovation\nNEES = error^T P^-1 error</div><p>NIS는 measurement prediction consistency, NEES는 state covariance consistency를 본다. dimension에 맞는 chi-square 범위와 장기 통계를 사용한다.</p></div>",
  "<div class='section'><h3>왜 RMSE만 최적화하면 위험한가</h3><p>R을 과도하게 키우거나 P를 과도하게 작게 만들면 특정 trajectory RMSE는 좋아져도 filter가 over/under-confident해질 수 있다. commissioning tuner가 consistency penalty를 같이 쓰는 이유다.</p></div>"
 ].join("")},
 lin:{group:"Hybrid estimator",title:"Lin — learned contact event로 contact-aided InEKF를 구동",lead:"Mini Cheetah에서는 4개 다리의 binary contact 조합을 16-class temporal classification으로 학습하고, 결과를 per-leg contact event로 사용한다.",chips:["learned contact configuration","temporal CNN","InEKF"],runtime:null,body:[
  "<div class='section'><h3>논문 구현</h3><div class='math'>150-frame history of 54-D features\\n[q,qdot,a,omega,foot position,foot velocity]\\n-> 2 Conv1D blocks + 3 FC layers\\n-> 16 contact configurations\\n-> decode per-leg contact events\\n-> add/remove contact states in InEKF</div></div>",
  "<div class='section'><h3>한계</h3><p>contact=true가 FK stationary constraint의 품질을 보장하지 않는다. slip/partial support를 한 비트로 표현하기 어렵다.</p></div>"
 ].join("")},
 youm:{group:"Hybrid estimator",title:"Youm NMN — NN이 body velocity를 measurement로",lead:"contact probability뿐 아니라 body linear velocity 자체를 learned pseudo-measurement로 InEKF에 추가한다.",chips:["GRU","neural measurement","velocity"],runtime:null,body:[
  "<div class='section'><h3>논문 구현</h3><div class='math'>[a,omega,q,qdot,q_des(prev)]\\n-> GRU(hidden 128) + MLP[256,128]\\n-> foot contact probabilities c_hat\\n-> body-frame linear velocity v_hat_body\\n\\ncontact probability -> leg-kinematics measurement gate\\nv_hat_body = R^T v + noise -> right-invariant IEKF measurement</div><p>실물 inference에서는 contact probability와 velocity에 LPF를 적용하고, contact는 0.5 threshold를 사용한다. learned velocity는 저속 bias 억제를 위해 조건부로 사용한다.</p></div>",
  "<div class='section'><h3>권한이 커진다</h3><p>Lin은 update gate를 학습하지만 Youm은 metric velocity measurement를 학습한다. sim-to-real bias가 더 직접적으로 들어올 수 있다.</p></div>"
 ].join("")},
 innkf:{group:"Hybrid estimator",title:"InNKF — physics filter posterior의 residual을 학습",lead:"InEKF를 버리지 않고 posterior가 남기는 systematic state error를 TCN이 예측해 Lie-group-consistent correction을 추가한다.",chips:["TCN","posterior residual","hybrid"],runtime:{observer:"residual"},body:[
  "<div class='section'><h3>논문 구조</h3><div class='math'>InEKF -> X_bar_plus\\n50-step history + X_bar_plus -> TCN -> 9 tangent coefficients\\neta_hat in se_2(3) -> E_hat = Exp(eta_hat)\\nX_bar_plusplus = E_hat^-1 X_bar_plus</div><p>중요: compensated X_bar_plusplus는 최종 출력이고 base InEKF state로 다시 feedback하지 않는다. 논문 TCN hidden은 [128,128,128,256,256].</p></div>",
  "<div class='section'><h3>CartPole 구현</h3><p>SO(2)-aware EKF posterior 뒤에 output-only residual MLP를 붙인다. corrected output은 base EKF로 feedback하지 않으며 base P를 corrected-output covariance라고 표시하지 않는다. 현재 v2 artifact의 held-out residual RMSE는 약 0.133에서 0.055로 감소했지만, offline residual 개선이 closed-loop 개선을 보장하지 않는다.</p></div>"
 ].join("")},
 coco:{group:"Hybrid estimator",title:"CoCo-InEKF — binary contact 대신 directional contact process covariance",lead:"각 persistent contact candidate의 body-frame velocity/process covariance를 연속적으로 학습한다. 이것은 FOCUS처럼 observation R만 조절하는 방식과 다르다.",chips:["process covariance","directional slip","differentiable InEKF"],runtime:null,body:[
  "<div class='section'><h3>논문 구현</h3><div class='math'>all contact candidates stay in filter state\nContactNet(history) -> 6 lower-triangular values L_i\nSigma_Ci = L_i L_i^T >= 0\np_Ci_dot = -R w_Ci,  w_Ci ~ N(0,Sigma_Ci)\n\nSigma_Ci enters contact process uncertainty Q</div><p>학습은 differentiable InEKF를 통한 BPTT와 body-frame velocity state-error loss로 수행한다. binary contact gating이 핵심이 아니다.</p></div>",
  "<div class='section'><h3>왜 CartPole 실행 모드를 연결하지 않나</h3><p>CartPole에는 persistent foot/contact-candidate states가 없다. 따라서 Adaptive-R을 CoCo 구현처럼 보여주는 것이 오개념을 만든다. 이 페이지는 논문 구조 설명만 제공한다.</p></div>"
 ].join("")},
  focus:{group:"Hybrid estimator",title:"FOCUS — contact가 아니라 FK measurement reliability",lead:"발이 닿았는지보다 그 발로 계산한 FK velocity를 지금 믿어도 되는지를 continuous weight로 학습한다.",chips:["continuous reliability","FK velocity","sensor history"],runtime:{observer:"adaptive"},body:[
  "<div class='section'><h3>핵심 식</h3><div class='math'>w_i in [0,1]\\nR_vel,i = R0 [1 + (1-w_i) S]\\ntau_i = clip(w_i/w_sat,0,1)\\nz_v,i = (1-tau_i) v_IMU + tau_i v_FK,i</div></div>",
  "<div class='section'><h3>Figure와 직접 연결</h3><p>Figure에서 contact source 품질이 velocity estimate와 closed-loop를 크게 바꿨기 때문에 measurement reliability가 현재 핵심 연구축이다.</p></div>",
  "<div class='section'><h3>CartPole 한계</h3><p>foot FK가 없으므로 FOCUS를 복제할 수 없다. 현재 Adaptive-R은 innovation-based outlier score로 observation R을 조절하는 구조적 bridge다. 같은 innovation으로 R을 바꾸므로 classical fixed-noise Kalman optimality를 주장하지 않는다. FOCUS의 learned per-foot reliability, FK/IMU velocity blending, foot-state Q modulation은 재현하지 않는다.</p></div>"
 ].join("")},
 sysid:{group:"Commissioning",title:"System Identification — tuning 전에 모델이 무엇을 틀렸는지 먼저 식별",lead:"controller weight가 잘못된 mass·inertia·friction·latency를 대신 보상하게 두면 sim2real에서 원인을 잃는다.",chips:["persistent excitation","physical parameters","identifiability"],runtime:null,body:[
  "<div class='section'><h3>현재 CartPole 예제</h3><p>exciting input trajectory에서 one-step prediction error를 최소화해 mc, mp, l, friction을 constrained CEM으로 식별한다. held-out transition error도 따로 확인한다.</p></div>",
  "<div class='section'><h3>중요한 전제</h3><p>데이터가 parameter를 구분할 만큼 excite하지 않으면 optimizer가 숫자를 내도 식별된 것이 아니다. parameter sensitivity/Fisher information, condition number, repeated trajectories를 확인해야 한다.</p></div>",
  "<div class='section'><h3>Humanoid</h3><p>physically consistent inertia, CoM, transmission/actuator constants, friction/compliance, kinematic offsets, latency를 분리해 식별한다. contact가 들어가면 contact wrench와 inertial parameter가 서로 설명을 빼앗지 않도록 experiment design이 중요하다.</p></div>"
 ].join("")},
 tuning:{group:"Commissioning",title:"Auto-tuning — parameter 종류에 맞는 optimizer를 고른다",lead:"모든 hyperparameter를 같은 black-box optimizer에 넣는 것은 좋은 commissioning이 아니다. differentiable, discrete, safety-critical, estimator calibration 문제를 분리한다.",chips:["DiffTune","Bayesian optimization","Safe BO","bilevel calibration"],runtime:null,body:[
  "<div class='section'><h3>방법 선택</h3><div class='math'>smooth MPC weights -> differentiable closed-loop tuning\ndiscrete horizon/solver -> BO / structured search\nhardware gains -> Safe BO\nQ_e,R_e,kinematics -> likelihood / bilevel calibration\ncontext-dependent gains -> contextual tuning</div></div>",
  "<div class='section'><h3>현재 evidence가 보여준 것</h3><p>CartPole CEM controller tuner는 train을 개선했지만 held-out validation/test를 악화해 reject됐다. 반면 consistency-aware estimator calibration은 held-out에서도 개선되어 accept됐다. optimizer보다 acceptance contract가 더 중요하다.</p></div>",
  "<div class='section'><h3>연결 연구</h3><p>DiffTune-MPC는 closed-loop objective에서 MPC cost parameter gradient를 구하고, legged Safe BO는 실제 하드웨어 gain을 safe set 안에서 탐색한다. 2026 bilevel estimator calibration은 covariance와 kinematic offset을 estimator-in-the-loop로 공동 보정한다.</p></div>"
 ].join("")},
 commissioning:{group:"Commissioning",title:"Commissioning — model을 맞추고, estimator와 controller를 따로/함께 검증한다",lead:"좋은 알고리즘을 고르는 것만으로 sim2real은 끝나지 않는다. 식별 → calibration → tuning → held-out validation → hardware-safe adaptation의 순서가 필요하다.",chips:["system ID","calibration","held-out validation","co-design"],runtime:null,body:[
  "<div class='section'><h3>권장 순서</h3><div class='math'>1. model/actuator/latency identification\n2. sensor + kinematic calibration\n3. estimator Q_e,R_e,P0 calibration + consistency\n4. controller Q_c,R_c,Qf,N,constraint tuning\n5. estimator-in-the-loop closed-loop tuning\n6. held-out domain randomization / worst-case validation\n7. safe hardware residual tuning\n8. runtime adaptation</div></div>",
  "<div class='section'><h3>이 repo에서 실제 제공</h3><p>src/commissioning.js가 constrained plant parameter identification, CEM-based controller tuning, estimator covariance calibration, train/validation/test split, stress report를 실행한다. 이 tuner 자체를 SOTA라고 주장하지 않고, Figure에서는 DiffTune/BO/Safe-BO/bilevel calibration으로 교체 가능한 공통 evaluation contract를 만드는 것이 목적이다.</p></div>",
  "<div class='section'><h3>절대 한 metric만 최적화하지 않는다</h3><p>controller는 tracking·effort·constraint margin·failure·actuator mismatch를 함께 보고, estimator는 RMSE뿐 아니라 NIS/NEES consistency를 같이 본다. tuned parameter가 validation/test에서 악화되면 채택하지 않는다.</p></div>"
 ].join("")},
 sim2real:{group:"Commissioning",title:"Sim2Real stress stack — mismatch를 한 층씩 켜서 실패 원인을 분리",lead:"한 번에 randomization을 모두 켜면 실패 이유를 모른다. model, sensor, bias, actuator lag/gain, command latency, outlier를 단독 scenario로 먼저 실행하고 마지막에 combined sim2real stack을 쓴다.",chips:["single-factor ablation","model mismatch","latency","actuator lag","sensor bias","held-out seeds"],runtime:{scenario:"sim2real"},body:[
  "<div class='section'><h3>현재 hidden mismatch preset</h3><div class='math'>mass / pole mass / length mismatch\n+ friction\n+ 0-2 control-tick command delay\n+ first-order actuator lag and gain error\n+ measurement noise\n+ sensor bias random walk\n+ external push when requested</div></div>",
  "<div class='section'><h3>무엇을 기록해야 하나</h3><p>command와 실제 applied command의 차이, state-estimation RMSE, max position/angle, control RMS, solver time, failure를 함께 기록한다. humanoid에서는 torque-speed, current-loop, thermal, contact/slip, joint compliance, network jitter가 추가된다.</p></div>",
  "<div class='section'><h3>Randomization의 역할</h3><p>randomization은 identification을 대신하지 않는다. 먼저 nominal model과 uncertainty bound를 데이터로 식별하고, 그 범위 안에서 train/calibration을 수행한 뒤 더 넓은 held-out/OOD 범위에서 failure boundary를 측정한다.</p></div>"
 ].join("")},
 faults:{group:"Commissioning",title:"Fault & degradation injection — noise가 아니라 고장/성능저하를 따로 본다",lead:"sim2real failure는 Gaussian noise만으로 설명되지 않는다. correlated noise, stale packet, stuck sensor, jitter, speed-dependent force limit, thermal derating을 각각 분리해 signature를 확인한다.",chips:["colored noise","dropout","stuck sensor","jitter","torque-speed","thermal"],runtime:{scenario:"colored"},body:[
  "<div class='section'><h3>센서 failure</h3><div class='math'>colored: n_k = rho n_(k-1) + sqrt(1-rho^2) sigma eps_k\\ndropout: hold-last + stale metadata\\nstuck: repeated value despite plant motion</div><p>white-Gaussian R tuning만으로 해결하려 하지 않고 innovation autocorrelation, timestamp freshness, fault isolation을 별도 진단한다.</p></div>",
  "<div class='section'><h3>actuator/transport degradation</h3><div class='math'>jitter: command hold / variable arrival\\ntorque-speed: F_max(v) decreases with |v|\\nthermal: sustained effort -> state T -> F_max(T) derating</div><p>humanoid에서는 motor current/voltage, torque-speed curve, drive bandwidth, thermal/current limits, bus voltage, scheduler jitter로 교체한다.</p></div>",
  "<div class='section'><h3>왜 중요하나</h3><p>같은 tracking error라도 원인이 sensor model, transport, actuator envelope, thermal state 중 무엇인지에 따라 수정해야 할 모델과 계층이 완전히 달라진다.</p></div>"
 ].join("")},
};
const CONTROL_LAB_TOPIC_ORDER=["overview","pid","lqr","linear_mpc","state_mpc","ltv_mpc","centroidal_mpc","full_nmpc","safety","robust_mpc","ppo","raw","kf","ekf","ukf","inekf","mhe","consistency","lin","youm","innkf","coco","focus","sysid","tuning","commissioning","sim2real","faults"];
if(typeof module!=="undefined")module.exports={CONTROL_LAB_TOPICS,CONTROL_LAB_TOPIC_ORDER};
